CREATE TABLE Partners (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	FirstName NVARCHAR(255) NOT NULL,
	LastName NVARCHAR(255) NOT NULL,
	Address NVARCHAR(MAX) NULL,
	PartnerNumber VARCHAR(20) NOT NULL,
	CroatianPIN VARCHAR(11) NULL,
	PartnerTypeId INT NOT NULL CHECK (PartnerTypeId IN (1, 2)),
	CreatedAtUtc DATETIME NOT NULL DEFAULT (GETUTCDATE()),
	CreatedByUser NVARCHAR(255) NOT NULL,
	IsForeign BIT NOT NULL,
	ExternalCode NVARCHAR(20) NOT NULL UNIQUE,
	Gender CHAR(1) NOT NULL CHECK (Gender IN ('M', 'F', 'N'))
);

CREATE TABLE Policies (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	PartnerId INT NOT NULL FOREIGN KEY REFERENCES Partners(Id) ON DELETE CASCADE,
	PolicyNumber NVARCHAR(15) NOT NULL,
	Amount DECIMAL(18,2) NOT NULL
);